Begin intro in competencies paper
CaptainSifff/paper_teaching-learning-RSE pull request #114
Opened 2023-09-11 19:52 UTC by CaptainSifff

2023-09-13 15:34 UTC, CaptainSifff commented
@mhagdorn , @hvwaldow I copied over a lot of parts from Jeremy's old introduction. This also brings back the old values section that we had.

2023-09-13 15:59 UTC, CaptainSifff commented
I have now added a one-page version for the survey.

2023-09-14 09:36 UTC, tobyhodges commented on competencies.md
> +acquire during training and formal education.
```suggestion
acquire during training and formal education.
By defining these competencies, 
we provide a framework to facilitate 
the training and continuous professional development of RSEs.
```

Trying to elaborate more on the "why" of the paper.

If not mentioned elsewhere already, I would also add another sentence about the range of competencies highlighting the breadth of expertise that RSEs bring to a project/team/institute.

2023-09-14 09:36 UTC, tobyhodges commented on competencies.md
> +Finally, the appendix provides an example curriculum
A curriculum for what?

2023-09-14 13:36 UTC, CaptainSifff commented on competencies.md
> +acquire during training and formal education.
In my opinion it is mentioned in the intro in lines 112 - 115:
 
>  Using this, Research Software Engineers are now people that 
> create or improve research software and/or the structures that the software interacts with
> in the computational ecosystem of a research domain.
> They are highly skilled team members who can also conduct their own research as part of their role.

and then kind of in lines 134-137:

> The skills themselves fall into three categories 
> 'software engineering', 'research' and 'team skills'
> reflecting the hybrid nature of an RSE.

And then, to exemplify the competencies in today's context we have the subsection
"RSE Tasks and Responsibilities" after the competencies. Is this what you had in mind?

2023-09-14 13:56 UTC, CaptainSifff commented on competencies.md
> +Finally, the appendix provides an example curriculum
oh well, you found the gap... Now we have #121

2023-09-14 15:11 UTC, tobyhodges commented on competencies.md
> +acquire during training and formal education.
Agree that this covers the second point I mentioned, but I think you still need at least one sentence that describes why the list of competencies could be useful. IMO we are not really doing that yet, stopping at "this is what we aimed to produce."

2023-09-14 19:58 UTC, jpthiele commented on competencies.md
> +Central to that code is the RSE's obligation to act in the public interest.
Not sure whether the public interest applies to all RSEs in industry.
For publicly funded research I wholeheartedly agree.
I'm fine with leaving this as is but thought it might be something to discuss. 
Or maybe to emphasize that for publicly funded research this is even more important?

2023-09-14 20:01 UTC, jpthiele commented on competencies.md
> +## Helpful academic RSE skills for researchers in an academic career
I don't like the doubled academic and would remove the first one. 
Especially since I would not consider most of the skills to be academic

2023-09-15 10:18 UTC, hvwaldow commented on competencies.md
> +Central to that code is the RSE's obligation to act in the public interest.
Not sure, depends on what **exactly** is conveyed by "public interest". The civil engineer needs to make sure the bridge doesn't collapse, even if there were no impact on the profits of his or her company. Isn't that "public interest" too?

2023-09-16 08:22 UTC, jlinx requested changes

2023-09-16 08:22 UTC, jlinx commented on competencies.md
> +infrastructure with education in the form of workshops and training.
```suggestion
SureSoft [@SURESOFTLink] is a DFG funded project at TU Braunschweig and
FAU Erlangen-Nürnberg fostering the sustainability of research software
by helping researchers adopt practices and tools from the software
engineering community [@SURESOFT2022]. Because tools are not enough on their own but require skill-full execution, the project implements a twofold approach that combines tools and
infrastructure with education in the form of workshops and training. 
```

2023-09-16 08:22 UTC, jlinx commented on competencies.md
> +infrastructure with education in the form of workshops and training.
The paragraph already summarizes the Suresoft project very well. I just added a little more "glitter".

The question remains if I should also add information regarding guidelines, policies etc.... but I think this is not relevant to the the focus of this paper. Is it?

2023-09-16 08:38 UTC, jlinx commented on competencies.md
> +Moreover, the approach of how "The Carpentries" are organized will be adopted.
With respect to the focus of the paper, I think we should stick to the activities regarding education. The above text summarizes it quite well in my view. The RSE workgroup of the NFDI infrastructure section as far as I know is addressing a more conceptual level and is not involved in educational purposes.

2023-09-18 08:17 UTC, mschwarzmeier commented on competencies.md
> +Central to that code is the RSE's obligation to act in the public interest.
Public interest might not always align with employer/boss goals as well as with individual goals. This is generally true for industry as well as academia.
It might be, that this problem is a bit more pronounced in industry as well as the 'public interest' does play a bigger role in academia.

I would fine with leaving this as is, too.

2023-09-18 08:24 UTC, mschwarzmeier commented on competencies.md
> +Moreover, the approach of how "The Carpentries" are organized will be adopted.
Ok, true. By pure change I know NFDI4Ing S2 is doing education ;-) 
Listing all the subsections involved seems to be too detailed: for NFDI4Ing I also fund  
- https://nfdi4ing.de/special-interest-groups-sig/training-education/ and 
- https://nfdi4ing.de/about-us/community-clusters/ and 
- https://nfdi4ing.de/base-services/s-6/ (community-based training on enabling data-driven science and FAIR data)  
  additionally to already mentioned 
- https://nfdi4ing.de/base-services/s-2/ (res.softw.dev)

I had thought of something very broad like 
> different sub-sections/groups within NFDI engage in educational matters where they teach their ideas/latest development.

If you don't like, resolve this discussion.

2023-09-18 16:53 UTC, CaptainSifff commented on competencies.md
> +infrastructure with education in the form of workshops and training.
I don't think we need to go into the detail of the initiatives. I would make an exception, if you have a very good overview page that you could link to.

2023-09-18 16:57 UTC, CaptainSifff commented on competencies.md
> +Central to that code is the RSE's obligation to act in the public interest.
I like to keep it like this. These are your values, that often you can only freely express if you're not constrained. Hence, if there are e.. economic constraints you still have these values, but their expression suffers.

2023-09-20 14:27 UTC, braunms commented on competencies.md
> +Moreover, the approach of how "The Carpentries" are organized will be adopted.
There is also some more content on NFDI4Ing in the [survey part](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/ad91ca6a894bc0ee2103280299430d21ca5915d9/survey.md?plain=1#L153C7-L153C7)

2023-09-22 10:33 UTC, merged

2023-10-05 17:39 UTC, CaptainSifff commented on competencies.md
> +Central to that code is the RSE's obligation to act in the public interest.
interestingly, also the original resource has this contradiction: https://ethics.acm.org/code-of-ethics/software-engineering-code/