Update example_career_path.md
CaptainSifff/paper_teaching-learning-RSE pull request #156
Opened 2023-10-27 08:18 UTC by ljgarcia

Some style- and grammar-related changes. The message remains the same.

2023-10-31 07:59 UTC, jlinx commented on example_career_path.md
> +For her, coding and sharing knowledge in the form of software is more exciting than writing a paper focused mostly on the obtained results.
Little provocative but I like the idea. However, I don't think the question is if she likes one or the other better. But, she likes the second (software publication option), too.

2023-10-31 08:32 UTC, jlinx reviewed
Some minor changes

2023-10-31 08:32 UTC, jlinx commented on example_career_path.md
> +For her, coding and sharing knowledge in the form of software is more exciting than writing a paper focused mostly on the obtained results.
Little provocative but I like the idea. However, I don't think the question is if she likes one or the other better. But, she likes the second (software publication option), too.

```suggestion
However, for her, coding and sharing knowledge in the form of software is of similar importance to writing a paper focused mostly on the obtained results.
```

2023-10-31 08:32 UTC, jlinx commented on example_career_path.md
> +These doctoral degrees are of course recognised by various funding agencies, such as the DFG, and hence enables RSEs that have chosen not to follow a research focused
Not so sure about this one.

```suggestion
These doctoral degrees are of course recognised by various funding agencies, such as the DFG, and hence enables RSEs that have chosen to not follow a research focused
```

2023-11-02 10:23 UTC, jpthiele commented on example_career_path.md
> +These doctoral degrees are of course recognised by various funding agencies, such as the DFG, and hence enables RSEs that have chosen not to follow a research focused
I'm also not sure. 
@jcohen02 any gut feelings on this as a native speaker?

2023-11-02 21:06 UTC, CaptainSifff requested changes
lloks perfect! thanks for the improvement! apart from one raised question we can merge it!

2023-11-02 21:06 UTC, CaptainSifff commented on example_career_path.md
> +The domain-agnostic RSE Master programme consists of a core of RSE topics with various electives for specialisation, some of them domain-specific (e.g., chemistry) or topic-specifi (e.g., cloud compu
```suggestion
The domain-agnostic RSE Master programme consists of a core of RSE topics with various electives for specialisation, some of them domain-specific (e.g., chemistry) or topic-specific (e.g., cloud computing for reserach).
```

2023-11-02 21:06 UTC, CaptainSifff commented on example_career_path.md
> +During her teaching duties, she becomes aware of a new project in her department that requires an RSE community manager,
Ah, OK, that's tricky....: What I meant was: an RSE that takes on the responsibility of managing a community (e.g. of domain scientist users).
I understand your correction, to mean a manager that manages a community of RSEs.

2023-11-03 10:50 UTC, ljgarcia commented on example_career_path.md
> +These doctoral degrees are of course recognised by various funding agencies, such as the DFG, and hence enables RSEs that have chosen not to follow a research focused
As far as I understand, "not to" is more formal than "to not".

2023-11-03 10:57 UTC, jcohen02 commented on example_career_path.md
> +These doctoral degrees are of course recognised by various funding agencies, such as the DFG, and hence enables RSEs that have chosen not to follow a research focused
I guess I would say that "not to" is more definite (and I suppose more formal) in that I think "to not" is perhaps a more relaxed way of saying the same thing - so yes, I agree with @ljgarcia, I think classing one as more formal than the other is correct.

2023-11-03 13:34 UTC, CaptainSifff commented on example_career_path.md
> +During her teaching duties, she becomes aware of a new project in her department that requires an RSE community manager,
Here we need to decide which viewpoint to take.

2023-11-03 16:42 UTC, CaptainSifff commented on example_career_path.md
> +During her teaching duties, she becomes aware of a new project in her department that requires an RSE community manager,
maybe I should stick to the original "community manager RSE"

2023-11-03 17:59 UTC, CaptainSifff commented
Oh, I'm so sorry.... This is the wrong file. The content has been merged into the main file competencies.md
I'll see which of your fixes still persist.

2023-11-03 18:20 UTC, merged