Some more contributions
CaptainSifff/paper_teaching-learning-RSE pull request #18
Opened 2023-05-18 10:22 UTC by jlinx

2023-05-18 17:47 UTC, jcohen02 requested changes
Thanks for this @jlinx. Apologies for my extensive editing and commenting. Hope the input is helpful and we can discuss during tomorrow's meeting or I'll just leave it with you to accept changes that you're happy with and reject those that you're not.

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
>  We have put forward the idea that familiarity with research is a prerequisite for an RSE in order to fit into the research space.
```suggestion
We have put forward the idea that familiarity with research is a prerequisite for an RSE in order to be able to work effectively in the research space and in collaboration with researchers. In this particular example, we consider a path into RSE via a traditional university route involving Bachelors and Masters degree studies that include an RSE element. However, we recognise that there are other routes into an RSE career and these are increasing. For example, some RSEs come from an industry background, others may come through apprenticeship or similar programmes. In both cases, gaining knowledge of the research lifecycle and understanding the ways that researchers work towards solutions to research challenges is something that can be developed on-the-job alongside training opportunities and the chance to work directly with researchers.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
>  This leads naturally to the question, whether it is possible to become an RSE without a home research domain.
Suggested some changes in the sections below. One point addressed in a couple of places is that people can graduate at any age and, indeed, become RSEs at any age - e.g. they may be retraining from another career path. I therefore think that inexperienced would be a better term so I've addressed this in the sections below.

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +It is of course not possible for everybody to do research into the research field of RSE, therefore we consider it much more useful if young graduates perform their research in a specific domain and
```suggestion
With software being a core element of the research process in so many different domains, it is not helpful for everybody working in RSE to have a background in computing or software engineering. Indeed, we consider it much more useful if new graduates looking to work in the RSE space come from a wide range of different domains. Expertise, beyond software development skills, in another research domain can be an important element of an RSE team being able to support RSE projects in that domain.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +In order for young RSEs to get their research experience we believe it is necessary that already in their master's thesis young RSE students are given computational research tasks that can be solved
```suggestion
In order for new and inexperienced RSEs to gain research experience, we believe it is necessary that students are given computational research tasks, as part of masters thesis work, that can be solved with the RSE specific skills of that domain. 
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +This gives them a Master's degree of a ${DOMAIN}-RSE that has learnt in their lectures a research domain specific part and a software engineering specific part, and enabled them to get a first dip in
```suggestion
This gives them a Master's degree of a ${DOMAIN}-RSE where the studies have included lectures covering research domain-specific topics alongside material covering software engineering skills and research software best practices. This enabled the student to get initial experience of real research work during their Master's thesis.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Of course, the next question for their future is whether a master's degree enables them to really be effective parts of a research group.
```suggestion
Of course, the next question for their future is whether a Master's degree serves as the only prerequisite needed to become an effective member of a research group.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +We argue that this is most likely not the case since they will not be accepted into research groups and there are formal barriers in the research landscape if people don't have a PhD (e.g. eligibilit
```suggestion
While we accept this is something of a generalisation, we argue that this is most likely not the case since undertaking a PhD provides a much more extensive set of research training and experience that can be vital for a researcher's future. Research environments different internationally but in many cases there are formal barriers in the research landscape that require a PhD (e.g. eligibility for funding).
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Hence a PhD is required to actively participate in science and why we argue the regular RSE should do a PhD that on one end combines knowledge of a research domain with software engineering heavy tas
Hence, in the context of this specific path, we consider that undertaking a PhD is an important element in being able to develop in the research environment and it's something that we argue research-focused RSEs should do. More specifically, we recommend undertaking a PhD project that combines domain research with large-scale computation in order to develop a strong research base around both the home domain and RSE.

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
>  This leads naturally to the question, whether it is possible to become an RSE without a home research domain.
Just a follow up to the comment above...as I've gone through this section making comments, I'm thinking that it feels increasingly contrived. I think it's making an argument that, at a general level, is not entirely valid. I think I understand what this is trying to cover and I've attempted to add some more context into the description.

Nonetheless, I can think of many highly-effective RSEs who don't have PhDs but who work and communicate extremely well with researchers and are ultimately able to produce very high quality research software outputs.

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +On the other hand, when pursuing a PhD, scientists are more and more required to do RSE work as part of their research.
```suggestion
On the other hand, when pursuing a PhD, scientists are increasingly required to do RSE-type work as part of their research as data and computation are becoming part of research tasks in a huge range of fields.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +It is not uncommon for scientists to be faced with RSE topics for the first time, because it has not been part of their academic curricula.
```suggestion
It is not uncommon for researchers to be faced with RSE topics for the first time, because it has not been part of their academic curricula.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Support from RSEs is one way to find a way out.
```suggestion
Support from RSEs is one way to resolve this challenge. 
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Another would be to lay the foundation for future RSE work already early in their curricula.
```suggestion
Another would be to lay more effective foundations for future RSE work at a much earlier stage in undergraduate/postgraduate studies.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Ideally, even establish dedicated master programs which specialise in RSE work.
```suggestion
We see scope for establishing dedicated RSE Master's programmes which specialise in developing RSE skills and practices.
```

2023-05-18 17:47 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +Examples would be Computational Sciences in Engineering (CSE) or Bio-Informatics.
```suggestion
Examples would be Computational Sciences in Engineering (CSE) or Bioinformatics. 
```

2023-05-18 18:46 UTC, jlinx commented on paper_teaching-learning-RSE.md
> +It is not uncommon for scientists to be faced with RSE topics for the first time, because it has not been part of their academic curricula.
Noticed that you (@jcohen02) prefer the term researcher over scientists. Need to ask you tomorrow about the difference...

2023-05-18 18:58 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +It is not uncommon for scientists to be faced with RSE topics for the first time, because it has not been part of their academic curricula.
🙂 Happy to discuss tomorrow but basically, I feel that software is relevant in so many domains and if we consider areas such as engineering, business, arts and humanities, for example, I don't think scientist is the right term to describe researchers in these fields? e.g. I think a Civil Engineering researcher would class themselves as an engineer but not a scientist? I see "researcher" as the most generic term for anyone undertaking research in any domain. Happy to change the terminology being used here if you prefer.

2023-05-25 08:16 UTC, jpthiele reviewed
Very nice additions! 
I found some typos and answered to some of Jeremys comments

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
>  Using that an RSE should be able to make predictions about a software's behaviour. This is a required skill for tasks like debugging, profiling, designing good tests, or predicting user interaction.
I think a comma after "Using that" is missing, right?

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +Oftentimes, a significant amount of effort in (research) software development needs to be spent on maintenance to ensure that software remains useful for researchers now and in the future. The resear
Comma after "If it isn't"?

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +While ensuring maintenance and sustainability of research software is of huge importance to the communities that build and use it, a particular challenge is that it's often very difficult to obtain o
small typo, communituy should be community

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +While we accept this is something of a generalisation, we argue that this is most likely not the case since undertaking a PhD provides a much more extensive set of research training and experience th
Should it not be "Research environments differ internationally, "?

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
>  This leads naturally to the question, whether it is possible to become an RSE without a home research domain.
I agree, it's a fine line between "how it currently is" and "how it should/could be". Nevertheless, taking current funding policies into account is a good thing to note here (and was already done). For example you can only hand in proposals to the DFG if you have a PhD...

2023-05-25 08:16 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +Hence a PhD is required to actively participate in science and why we argue the regular RSE should do a PhD that on one end combines knowledge of a research domain with software engineering heavy tas
I'm not sure whether "large-scale computation" fits in every domain. To me it sounds a bit too much like HPC which is a very STEM thing and even there mostly EM + Physics.

2023-05-26 12:52 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
>  Using that an RSE should be able to make predictions about a software's behaviour. This is a required skill for tasks like debugging, profiling, designing good tests, or predicting user interaction.
Me, too.

2023-05-26 13:05 UTC, CaptainSifff approved these changes
Will merge the branch later on, so that we can focus on new things. 
and I will try to fix the reminaing typos.
Thanks!

2023-05-26 13:05 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
>  This leads naturally to the question, whether it is possible to become an RSE without a home research domain.
I've added that to the main branch... forgot we had that discussion over here...

2023-05-26 13:14 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +Oftentimes, a significant amount of effort in (research) software development needs to be spent on maintenance to ensure that software remains useful for researchers now and in the future. The resear
I think [CAA] (https://caa-international.org/about/) might not approve of the suggested term

2023-05-26 17:53 UTC, merged