Feedback on tables
CaptainSifff/paper_teaching-learning-RSE pull request #184
Opened 2023-11-10 23:31 UTC by MakisH

FYI @CaptainSifff @jngrad. Closes #168.

## Career-level table

- [x] Adds/edits some content, where annotated.
- [x] Fixes the width of the first column. Apparently, the width of the columns is defined as a ratio of the number of dashes per column. To make the first column thinner, add more dashes in the other columns.
- [x] Splits the table into three, grouped by skill set. This avoids a page break, lets the reader take a breath when reading these tables, and generally makes pagination easier.
- [x] Converts everything to "Should", everything starts with uppercase, everything ends with a period.

Rendering:

![Screenshot from 2023-11-11 00-24-11](https://github.com/CaptainSifff/paper_teaching-learning-RSE/assets/4943683/1bbc8765-4656-49dd-9430-2a25de442284)

## Team-structure table

TODO

2023-11-13 17:18 UTC, MakisH reviewed
@CaptainSifff This is now ready for review.

@jcohen02 I got the impression that you mainly worked on these tables before, so please have a look as well.

I think I did not change the meaning anywhere apart from the places annotated. I dropped most of my lukewarm suggestions I discussed with @CaptainSifff and @jngrad, I think they are not needed.

2023-11-13 17:18 UTC, MakisH commented on competencies.md
> +  often self-taught.
Some clarifications regarding the roles.

2023-11-13 17:18 UTC, MakisH commented on competencies.md
> +  These can be read as policy/action recommendations.
I have formulated everything as a "Should...", so I think we can recommend these as actions/policies. This could attract more attention to these tables.

2023-11-13 17:18 UTC, MakisH commented on competencies.md
> +The current situation may differ.
Disclaimer to help the reader understand the viewpoint. Previously, some items read as "this is how it currently is", while some other items were "this is what an RSE should know". I am still not completely happy with the formulation.

I would read this table as "I am an organization and I need RSEs. Do I need to invest more on individual RSEs, groups of RSEs, local, or team-based? What should I do to help them?

Not sure how to best convey this.

2023-11-13 17:18 UTC, MakisH commented on competencies.md
> +      such as an RSE curriculum, as described in~\autoref{subsec:examplemaster}.
Added a reference to the M.Sc. RSE of the appendix.

2023-11-13 20:30 UTC, CaptainSifff commented on competencies.md
> +The current situation may differ.
the organization column can have a more demanding tone, in order to promote change?

2023-11-13 21:34 UTC, MakisH commented on competencies.md
> +The current situation may differ.
You mean changing "should" to "must"? I guess that is maybe too demanding, isn't it?

2023-11-14 10:15 UTC, jcohen02 commented on competencies.md
> +The current situation may differ.
I think the reason for using "should" here was that we know, in reality, that it's not going to be practical for organisations to adopt all these recommendations/ideas/guidelines in a comprehensive way - if we say "must" it seems rather unrealistic. Saying that they "should" do something is aimed to highlight that to enable positive change, this is a guideline that "should" be followed. Does that make sense?! 🤔

2023-11-14 12:33 UTC, CaptainSifff commented on competencies.md
> +The current situation may differ.
I though more along the following(avoiding the use of must):
Instead of "should offer training and other resources in core topics to support indivdual developers. Should have research software guidance/policies that provide advice" to have sth. like:
Training and other resources in core topics that support individual developers is present. Actionable Research Software guidance/policies are in place.

2023-11-14 12:39 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
The use of the word *recommend* triggers my sense, that it might be worthwhile that we actually denote the presence of this section somewhere in th eintro.

2023-11-14 12:42 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
and thereby it supplements the reference Katerbow2018 in our bibliography.

2023-11-14 12:50 UTC, CaptainSifff requested changes

2023-11-14 12:50 UTC, CaptainSifff commented on competencies.md
>  to and support them. Some of them are brought to life in the example career path of the appendix.
While at it, we should add the proper markdown reference to the appendix here.

2023-11-14 13:59 UTC, MakisH commented on competencies.md
> +The current situation may differ.
I don't like the "is present" / "are in place", because it does not sound as recommendation. It is then also confusing whether it is the current situation or a utopia.

I have the impression that "should" is also the form used in other parts of this paper.

2023-11-14 16:25 UTC, MakisH commented on competencies.md
>  to and support them. Some of them are brought to life in the example career path of the appendix.
Added:

![Screenshot from 2023-11-14 17-25-08](https://github.com/CaptainSifff/paper_teaching-learning-RSE/assets/4943683/508f4d1f-47e5-4cb5-b294-46c66686bd3d)

2023-11-14 18:15 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
perfect! What about mentioning the DFG reference? I don't quite have an idea, where to fit it in.

2023-11-14 18:25 UTC, MakisH commented on competencies.md
> +  These can be read as policy/action recommendations.
I don't see how https://www.dfg.de/formulare/50_01/50_01_en.pdf could fit in the recommendations for organizations. DFG is an organization, sure, but why mention it in this context?

2023-11-14 19:10 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
not this one, i meant Katerbow2018. this leads here: https://zenodo.org/records/1172988

2023-11-14 19:11 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
it also provides recommendations for organisations, and also the hierarchy levels in between.

2023-11-14 19:37 UTC, jcohen02 requested changes
Great work @MakisH and @CaptainSifff, this section is looking good now. In particular, I think tables 4-6 are really good. When reading through, I felt that they really bring out the nuances that I was trying to capture when I originally restructured the table to include the split between locally-based and RSE team-based for each of the individual or group-based sections.

I wonder if some of the content in the earlier tables covering Junior/Senior/Principal RSEs still feels like it may perhaps be a little artificial/contrived but I don't think there's much we can do about that - it's a large space and none of these role levels are really all that well defined within the wider RSE community yet. I think it's more important to try and make the distinction between the different levels of RSE roles as we've done in the table so this is still an important set of content.

I've suggested some minor modifications, sorry to do this after you've already spent quite some time going through this section. I've marked my review as changes requested but I'll leave it with you to decide what you want to incorporate and what you want to leave out for now - feel free to go ahead and merge whenever you're ready.

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +| USERS      | Should be able to communicate with non-SE users of the project.                                                               | Same as junior RSE, and be able to interpret the feedbac
It feels like something is missing here in the Principal section (or maybe it's just the full stop?! 🙂). Anyway, here's a suggested update:
```suggestion
| USERS      | Should be able to communicate with non-SE users of the project.                                                               | Same as junior RSE, and be able to interpret the feedback.                                                                            | Same as senior, and should also be able to effectively take feedback into account when steering the project.                                                                    |
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
>  - Senior RSE: They have gained experience and can set the standards in a software project.
I can't add a comment to the above line for Junior RSE but a suggested rewording to the Junior RSE text:
" - Junior RSE: These are people who are in the earlier stages of their RSE career journey, but they should still have the skills to contribute reliable and well-structured code to software projects."

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
>  or when they are based in a dedicated RSE team.
Maybe add "centralised" to the RSE team? e.g. 
```suggestion
or when they are based in a dedicated, centralised RSE team.
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +  do to support the RSEs at the different team structures.
```suggestion
  do to support the RSEs in the context of the different team structures.
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +    May want to develop reusable shareable outputs for a specific case. Needs easy resources.&
In general this section is great, I'm just a little unclear what is meant by "Needs easy resources."? Is this "Needs easy access to resources." or "Needs access to easy to use resources.", or maybe something different - I think this is probably written as it is because we're very constrained on space here but I think it would be good to add a slight clarification here if possible.

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +      a key expertise of an RSE team.&
```suggestion
      a key area of expertise for an RSE team.&
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +    Should raise awareness about software as publishable scientific output, provide recommendations and checklists to support software-publications, and have legal experts in place to deal with compl
```suggestion
    Should raise awareness about software as a publishable scientific output, provide recommendations and checklists to support software publications, and have legal experts in place to offer advice on complex cases.
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +      and maintenance of the software for external users.&
Suggesting a minor addition here:
```suggestion
      and maintenance of the software for external users. Resourcing for future maintenance may be a challenge.&
```

2023-11-14 19:37 UTC, jcohen02 commented on competencies.md
> +    Is well-organised, in order to be able to transfer the codebase to future developers.&
I didn't want to change this but I think this currently represents an aim rather than widely-applied current practice - I guess that's what this table is trying to do, so maybe it's fine, but I think that it's more common, at the moment, for a lone developer within a research team (especially if they're a researcher rushing to get results for a paper deadline, for example!) to neglect key project management approaches that can support sustainability of code. That's a generalisation and there will of course be some researcher/developers who are super organised with these things but traditionally, I don't think that's always been the case.

2023-11-14 19:59 UTC, MakisH commented on competencies.md
> +  These can be read as policy/action recommendations.
The Katerbow2018 I have already integrated, see just above, last screenshot (citation [32]).

2023-11-14 20:01 UTC, MakisH commented on competencies.md
> +| Competency | Junior RSE                                                                                                                    | Senior RSE
I agree, I thought there was a good reason to have it there. Thanks for bringing this up!

2023-11-14 20:06 UTC, MakisH commented on competencies.md
> +| LIBS       | Should be able to use package distribution platforms.                                                                         | Same as junior, but should set the project standard and
I am adding all the suggestions, but I may need to reword some for pagination reasons later.

2023-11-14 20:11 UTC, MakisH commented on competencies.md
> +      and maintenance of the software for external users.&
I am adding this, but I think it is rather clear that when one is working alone, they cannot guarantee that there will be resources in the future.

2023-11-14 20:14 UTC, MakisH commented on competencies.md
> +    Is well-organised, in order to be able to transfer the codebase to future developers.&
>  think this currently represents an aim rather than widely-applied current practice - I guess that's what this table is trying to do, so maybe it's fine

Indeed, this table is now shaped to have the aim perspective. Previously, it was rather mixed. I have also added a disclaimer in the main text that reality may differ.

2023-11-14 20:16 UTC, jcohen02 commented on competencies.md
> +      and maintenance of the software for external users.&
I think my comment was driven more by the fact that resourcing was mentioned in one of the other columns but not here - if you're happy to add it that's great, but if space is an issue, feel free to remove it.

2023-11-14 20:35 UTC, MakisH commented on competencies.md
>  - Senior RSE: They have gained experience and can set the standards in a software project.
Added manually, thanks!

2023-11-14 20:48 UTC, MakisH commented on competencies.md
> +    May want to develop reusable shareable outputs for a specific case. Needs easy resources.&
This was written like this before I jump in, and I have no clue what it is supposed to mean. `git blame` tells me that @CaptainSifff may be able to help us here:

https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/19/commits/79b99001e4d022f1554867ccfd7fa9031a3ad3ba

2023-11-14 20:54 UTC, MakisH commented on competencies.md
> +    Is well-organised, in order to be able to transfer the codebase to future developers.&
Besides, the current formulation sets a very low barrier. It essentially tells "don't dump your complete `/home/` in a zip file to give to the next people before disappearing from the face of Earth".

I reformulated this to "Is organised enough to be able to...". This should be clearer.

2023-11-14 20:58 UTC, MakisH commented on competencies.md
> +| SWREPOS    | Should seamlessly interact with the repository of their project.                                                              | Should be well-versed in the intricacies of a repository
Very good point! Also, the formulation before did not make complete sense.
Fixed it.

2023-11-14 21:00 UTC, MakisH commented on competencies.md
> +The current situation may differ.
@jpthiele what do you think on the format of these recommendations? Is the "Should..." fine, or should we explore other options?

2023-11-14 21:07 UTC, MakisH commented on competencies.md
> +    May want to develop reusable shareable outputs for a specific case. Needs easy resources.&
Replaced `Needs easy recources.` with `Needs clear guidelines.`, as I assume this is the main challenge of a local team.

2023-11-14 21:15 UTC, MakisH commented
@jcohen02 I implemented all your suggestions. Size-wise, every table still fits nicely in one page.

There are now only three unresolved discussions:

1. Citations in the recommendations: I think this is already implemented.
2. Phrasing of recommendations ("should"/"must"/...): I and @jcohen02 think that the "should" is fine. I think this is just a language-related misunderstanding.
3. In the LIBS, it was unclear what "Needs easy resources" means. I think now it should be fine.

You can find the current rendering of the tables in the first comment.

2023-11-15 00:20 UTC, CaptainSifff commented on competencies.md
> +    May want to develop reusable shareable outputs for a specific case. Needs easy resources.&
Guidelines sounds perfect here. the easy was meant to mean, that the available guidelines should be easily available to the users, because they would not follow them.

2023-11-15 00:21 UTC, CaptainSifff commented on competencies.md
> +  These can be read as policy/action recommendations.
Great! Have I looked into the wrong branch again....?

2023-11-15 00:38 UTC, CaptainSifff approved these changes

2023-11-15 00:38 UTC, CaptainSifff commented on competencies.md
> +The current situation may differ.
then, it's should.

2023-11-15 00:47 UTC, merged

2023-11-15 09:39 UTC, jcohen02 commented
> @jcohen02 I implemented all your suggestions. Size-wise, every table still fits nicely in one page.
> 
> There are now only three unresolved discussions:
> 
>     1. Citations in the recommendations: I think this is already implemented.
> 
>     2. Phrasing of recommendations ("should"/"must"/...): I and @jcohen02 think that the "should" is fine. I think this is just a language-related misunderstanding.
> 
>     3. In the LIBS, it was unclear what "Needs easy resources" means. I think now it should be fine.
> 
> 
> You can find the current rendering of the tables in the first comment.

Many thanks for your work on this @MakisH. All looks good and I see this has been merged now but just to confirm, I agree with point (3), it looks fine, and I also think everything "should" now be OK in relation to point (2) also! 🙂

2023-11-15 11:08 UTC, jngrad commented on competencies.md
> +The current situation may differ.
I find the formulation "The current situation may differ" a bit unclear; replacing "current" by "actual" or "present-day" would probably bring this sentence closer to the original meaning, although I'm not totally satisfied with these options either. The formulation "this is how it currently is" is probably the clearest, but maybe I'm overthinking it.

2023-11-15 11:08 UTC, jngrad reviewed
Never too late to say thanks @MakisH !

2023-11-15 15:41 UTC, MakisH commented on competencies.md
> +The current situation may differ.
@jngrad How about "The **observed** situation may differ"?

2023-11-15 17:03 UTC, jngrad commented on competencies.md
> +The current situation may differ.
I looked for alternatives too, like "The state of affairs may differ" (a bit dramatic), or "Your mileage may vary" (too direct, could also be interpreted as condescending). But no matter how I look at it, the phrasing just feels weird to me, perhaps because the statement is redundant with the phrase above it, which already introduced the tables as *expectations*. Let's keep the text as-is, it's no big deal anyway.