first draft for the required number of RSEs
CaptainSifff/paper_teaching-learning-RSE pull request #23
Opened 2023-05-26 12:31 UTC by CaptainSifff

So, as promised I created  numbers on the number of required RSEs.
Feel free to discuss!

2023-05-26 13:38 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +In public research alone we have better numbers and there have been 71733 researcher in 2020.
What exactly is meant by public researches, if OECD lists government researchers? University only? University + Helmholtz, RKI, DLR, etc.?

2023-05-26 13:39 UTC, jpthiele approved these changes
mostly missing punctuation. 
Depending on what public researchers means the calculations seem sound estimates to me.

2023-05-26 13:39 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +In order to set up the argument for dedicated RSE education we need to estimate the number of required graduates.
argument,

2023-05-26 13:39 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +In public research alone we have better numbers and there have been 71733 researcher in 2020.
71,733 (otherwise it's hard to compare) researcher**s**

2023-05-26 13:39 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +If we assume that half of the workforce is made up by researchers coming from other graduates and the other half are properly minted
How about "from domain specific graduation programs"?

2023-05-26 13:39 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +RSE graduates this yields that there is a requirement of around four dedicated RSE education places each producing graduating classes
graduates, 
"requirement for" instead of "of"?

2023-05-27 22:33 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +In order to set up the argument for dedicated RSE education we need to estimate the number of required graduates.
In this context, I think I'd say the comma is not required...

2023-05-27 22:41 UTC, jcohen02 requested changes
Suggesting a few possible edits/changes. We may want to revisit this as we complete other elements of the paper and see how everything ties together - maybe that will also help us to have a better idea of how realistic this is and offer some more evidence to support the figures?

2023-05-27 22:41 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +In order to set up the argument for dedicated RSE education we need to estimate the number of required graduates.
In this context, I think I'd say the comma is not required...

2023-05-27 22:41 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +In public research alone we have better numbers and there have been 71733 researcher in 2020.
Suggested edit:
```suggestion
In public research alone we have better numbers and 71,733 researchers were recorded in 2020.
```

2023-05-27 22:41 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +RSE graduates this yields that there is a requirement of around four dedicated RSE education places each producing graduating classes
Also, maybe "suggests" rather than "yields"?

2023-05-27 22:41 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +This calculation assumes that RSEs do not move into into industry with their skillset.
```suggestion
This calculation assumes that RSEs remain within the research community and do not move into industry with their transferable skillset.
```

2023-08-04 11:50 UTC, jcohen02 commented
From discussion at the meeting on 04-08-2023, we like this content but recognise that the predictions here are likely to have significant inaccuracies because there are a lot of assumptions made.

On this basis, we're not sure that this is necessarily relevant for the initial output focused on competencies but are keen to include this and revisit in due course.

@CaptainSifff, could we deal with the `FIXME` in the content and then merge this?

2023-08-14 19:43 UTC, merged