Suggest changes to SE skills section
CaptainSifff/paper_teaching-learning-RSE pull request #231
Opened 2024-01-23 15:22 UTC by annalenalamprecht

Here is my long-promised suggestion for changes to the section on SE skills. Some words on the motivation behind these changes: 
* First suggestion is to rename "software engineering skills" to "technical skills". This is in particular motivate by the fact that things like re-use and teamwork that are included in the research and communication skills are also usually regarded SE skills. I think it makes sense to focus here on the technical aspects in contrast. Also, it makes it a bit easier to motivate why RSE is different from "standard" SE.
* Then I would suggest to mention the life cycle as first item in the list, as at least DOCBB and LIBS build upon that. I enriched the SWLC with a number of standard technical terms from SE, to show that all these things also have their place in RSE (albeit often in different forms).
* MOD seems to be the skill to me that in SE is commonly called "program comprehension" so I added that term. 

So far for this PR. I have some more comments on the paper, but they will go another route.

2024-01-24 10:00 UTC, BeastyBlacksmith approved these changes
Does make sense to me and reads very well. Just need to fix the typos

2024-01-24 15:35 UTC, mschwarzmeier commented on competencies.md
> +and be able to predict and cater to the changing needs a software project as it moves through the stages.
```suggestion
and be able to predict and cater to the changing needs of a software project as it moves through the stages.
```

2024-01-25 14:01 UTC, jpthiele commented
Overall, the changes make a lot of sense. Thank you!

I am however unhappy with the new name of 'technical skills' since some of the R and comm skills to some part are technical, (PM) without technical tools seems like a glass half full and (DOMREP) as well as 'Software publication' are also partially technical. 

Maybe it has to be some combination like 'technical software skills' or something along those lines.

2024-01-25 14:47 UTC, mhagdorn commented
> Overall, the changes make a lot of sense. Thank you!
> 
> I am however unhappy with the new name of 'technical skills' since some of the R and comm skills to some part are technical, (PM) without technical tools seems like a glass half full and (DOMREP) as well as 'Software publication' are also partially technical.
> 
> Maybe it has to be some combination like 'technical software skills' or something along those lines.

I see the term _technical skills_ in the context of the other two pillars, _research_ and _communication skills_. They are all neutral and snappy terms. I think taking those three pillars together it is clear that technical skills are the base software engineering skills. The research skills are the add-ons that make RSEs somewhat different. Both SE and researchers need to have communication skills. They all contain aspects of each other. I take PM tools as productivity tools, ie like a spreadsheet program (I know some people use them for data management...). In the same vein I have no clue how to operate the new fangled teams conference hardware....

We do have both SWREPOS and DOMREP. My understanding is that SWREPOS cover the technical details of using repos and version control. While DOMREP is about knowing your way around of specific repos that are relevant to a particular field.

2024-01-25 22:06 UTC, CaptainSifff requested changes

2024-01-25 22:06 UTC, CaptainSifff commented on competencies.md
> +form a mental model of a piece of software in a specific environment (program comprehension).
I like that word. Although I wonder whether it is as comprehensive as the MOD skill over here. Which as @unode pointed out is actually more like the "Scientific Method".

2024-01-25 22:06 UTC, CaptainSifff commented on competencies.md
> +  - Software engineering module: Here we develop foundational software engineering competencies (basic knowledge and skill regarding requirements engineering, software architecture and design, implem
The meaning has changed here.... The Software Development tools, we would have placed into Digital Ecosystem Module, whereas the architecture part over here, is more like the high-level view of how to grow big softwares.

2024-01-26 11:05 UTC, MakisH commented on competencies.md
> +Initial development generally involves an analytic process where needs and ideas are gathered and analysed (requirements engineering),
I had a similar feeling, but I think only because this sentence is now removed:

> Often the development is iterated.

Was this intentional? Because I don't see any conflict with the rest of the additions.

I do like using the formal terms here. I understand that these are still totally part of iterative development, just in more than one iteration.

2024-02-01 13:24 UTC, mschwarzmeier commented on competencies.md
> +and be able to predict and cater to the changing needs of a software project as it moves through the stages.
I don't see, how to predict changing needs beyond the most obvious ones.

2024-02-12 19:45 UTC, annalenalamprecht commented on competencies.md
> +Therefore, we categorise the competencies into three categories: *technical skills*,
I thought about this again, but next to "research skills" and "communication skills" I still think "technical skills" is the most appropriate among the suggestions circulated thus far. "Communication" also does not pick up anything from RSE, so that is not the pattern here.

2024-02-12 20:05 UTC, annalenalamprecht commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
not mentioning version control here is fine with me

2024-02-12 20:11 UTC, annalenalamprecht commented on competencies.md
> +  - Software engineering module: Here we develop foundational software engineering competencies (basic knowledge and skill regarding requirements engineering, software architecture and design, implem
I guess we can remove the "practicalities ..." part here, especially as the importance of practical projects is emphasized a little later in the paper.

2024-02-12 20:12 UTC, annalenalamprecht commented on competencies.md
> +and be able to predict and cater to the changing needs of a software project as it moves through the stages.
@mschwarzmeier What exactly is your question/point here?

2024-02-14 14:08 UTC, sdruskat commented on competencies.md
> +Therefore, we categorise the competencies into three categories: *technical skills*,
I agree with @annalenalamprecht here. I've recently talked about some of the major differences between SE and RSE, and things like navigating software citation and publication have a strong technical component, but not a software engineering component. (In other contexts one could frame them as being the skills that set RSE apart from SE, but calling them "research software engineering skills" would drop us deep into infinite recursion.)

2024-02-14 14:32 UTC, sdruskat commented on competencies.md
> +Initial development generally involves an analytic process where needs and ideas are gathered and analysed (requirements engineering),
@annalenalamprecht Will a reviewer with an RE background agree with this definition of requirements engineering?

I'm asking because a) I think it is a good definition (for the RSE context), but b) RE (at least in SWEBOK) has a systematic component ("the systematic handling of requirements"), which I think c) is seldomly found in RSE. Not because of subpar practice necessarily, but more due to the experimental and highly agile nature of much of RSEng.

I don't have strong feelings, but if you feel that this is relevant, perhaps this could be picked up in the paragraphs below, where you talk about the research software life-cycle? (Although c) is also only based on intuition with no reliable data to support. Sooo much still to do!)

2024-02-14 14:47 UTC, sdruskat commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
As far as I can see in current `main`, "version control" as a skill is only mentioned in passing in Appendix A. This is widely at odds with current teaching practice, where VCS is one of the early and central (perhaps *the* central) skill taught to researchers (see, e.g., The Carpentries curricula, but also Helmholtz & DLR practice). 

I see the point you are making @CaptainSifff, but think it'd be _very_ odd not to mention version control here at all!

In fact, I think that the current wording is a bit too abstract to explain the use of SWREPOS in the tables further down, where, e.g., Table 1 says "Should seamlessly interact with the repository of their project.", where *repository* to me clearly points to a version control repo! I'll make a change suggestion to that effect.

2024-02-14 14:48 UTC, sdruskat commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
```suggestion
The RSE should be able to identify and use fitting public platforms (so-called software source code repositories or "repos" with version control) 
```

2024-02-14 14:49 UTC, sdruskat commented on competencies.md
> +to share the artefacts they have created and invite the public to scrutinise them for public review.
```suggestion
to share the code artefacts they have created and invite the public to scrutinise them in public reviews.
```

2024-02-14 14:50 UTC, sdruskat commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
This and below comment because this skill (to me!) clearly refers to source code repos on remote public platforms, as opposed to local source code repos, or remote repos of another kind (e.g., open access repositories).

2024-02-14 17:15 UTC, mschwarzmeier commented on competencies.md
> +and be able to predict and cater to the changing needs of a software project as it moves through the stages.
I am not sure, I fully understand this sentence. Maybe an example could help?

2024-02-14 17:28 UTC, mschwarzmeier commented on competencies.md
> +to share the artefacts they have created and invite the public to scrutinise them for public review.
I know the skill is called SWREPOS, but I kinda liked the old formulation, where the artefacts were less defined. It is not a strong opinion though.

In our work on simulation software and models, it is fundamental for the understanding, that there are jupyter notebooks, showing some charts/.... For further development they are essential and therefore cannot be separated from the code. Of course the notebooks/created graphs also belong to the publications we are doing with that code.
In another project of my group, these graphs were actually displayed on gitlab-pages, so there was a tight coupling to VCS.

2024-02-15 13:17 UTC, jpthiele commented on competencies.md
> +Therefore, we categorise the competencies into three categories: *technical skills*,
The more I think about it the more I agree with technical skills. So fine by me.

2024-02-15 13:21 UTC, jpthiele commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
And even thinking of the future of automation. I'd still want some form of versioning to be able
to point to the specific version I used to do my computations.
So I'd still have to somehow interact with it.

2024-02-15 13:22 UTC, jpthiele commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software repositories or repos with version control)
Oh and who would be most likely to automate the version control aspect of research?
Us RSEs probably xD So we should still know how it works to be able to maintain the software.

2024-02-16 10:13 UTC, CaptainSifff commented
We decided to postpone this discussion to next friday 23.02

2024-03-01 09:51 UTC, CaptainSifff commented
Use Software Skills.

2024-03-01 09:57 UTC, jpthiele commented on competencies.md
> +and be able to predict and cater to the changing needs of a software project as it moves through the stages.
This has just been moved from a different position in the paper is not really a new addition.
So let's just keep it as is for now.

2024-03-14 23:09 UTC, CaptainSifff commented on competencies.md
> +to share the artefacts they have created and invite the public to scrutinise them for public review.
> I think I get your point, and have no strong feelings about this one particular change here (but do about the one above).
> 
> On the other hand, whether you commit notebooks, source files, config files, etc., these are all code (even Markdown files and - one could argue - ASCII/plaintext files). Similarly, the pages rendering are what you do with the code files, so are derived artifacts (and code themselves, HTML, CSS, etc.)...
> 
> Anyway, I'll let others be the judge of whether this change suggestion should be accepted.

I'm in @mschwarzmeier team here. I chose the wording with the intent of also being inclusive future developments.

2024-03-15 08:54 UTC, mhagdorn commented on competencies.md
> +to share the artefacts they have created and invite the public to scrutinise them for public review.
I agree with @CaptainSifff and @mschwarzmeier, I prefer the less well defined formulation: code implies to me something that gets transformed. As much as it pains me, sometimes it is really useful to store outputs in a repo. In some cases (like notebooks) you don't have a choice. In any case I don't think we gain from sharpening the term, if anything we will confuse people.

2024-03-26 16:19 UTC, CaptainSifff commented on competencies.md
> +Therefore, we categorise the competencies into three categories: *technical skills*,
```suggestion
Therefore, we categorise the competencies into three categories: *softeware/technical skills*,
```
In the meantime I like the "/" construct better. On the one hand we still make it obvious that we are for software, on the other hand we are an instance of Research *T*echnical professionals.

2024-03-26 16:20 UTC, CaptainSifff commented on competencies.md
> +## Technical skills
```suggestion
## Software/Technical skills
```
Be consistent.

2024-03-26 17:33 UTC, CaptainSifff commented on competencies.md
> +that things work as expected and that they continue to do when develoment progresses further.
```suggestion
that things work as expected and that they continue to do when develoment progresses further. Depending on the software project, this can mean a simple "Think-before-you-do", or more elaborate and formal processes.
```

2024-03-26 17:34 UTC, CaptainSifff commented on competencies.md
> +as well as software retirement.
```suggestion
as well as software retirement.
```

2024-03-26 17:49 UTC, CaptainSifff commented on competencies.md
> +and be able to predict and cater to the changing needs of a software project as it moves through the stages.
Reminder to Flo: I think currently it's duplicated.

2024-03-26 18:03 UTC, CaptainSifff commented on competencies.md
> +  - Software engineering module: Here we develop foundational software engineering competencies (basic knowledge and skill regarding requirements engineering, software architecture and design, implem
```suggestion
  - Software engineering module: Here we develop foundational software engineering competencies (basic knowledge and skill regarding requirements engineering, software architecture and design, implementation, quality assurance, software evolution), again emphasizing and strengthening (\gls{DOCBB}, \gls{LIBS}) on a more abstract level.
```

2024-03-26 18:25 UTC, CaptainSifff commented on competencies.md
> +The RSE should be able to identify and use fitting public platforms (so-called software source code repositories or "repos" with version control)
```suggestion
The RSE should be able to identify and use fitting public platforms (so-called software repositories or "repos")
```

2024-03-26 18:27 UTC, CaptainSifff commented on competencies.md
> +to share the code artefacts they have created and invite the public to scrutinise them in public reviews.
```suggestion
to share the artefacts they have created and invite the public to scrutinise them in public reviews.
```

2024-03-26 18:34 UTC, CaptainSifff commented on competencies.md
>  | \gls{SWREPOS}    | Should seamlessly interact with the repository of their project.                                                              | Should be well-versed in the intricacies of a repo
```suggestion
| \gls{SWREPOS}    | Should seamlessly interact with the repository of their project.                                                              | Should be well-versed in the intricacies of a repository, and probably interact with repositories of multiple projects.               | Should promote the use of repositories and be able to convey best practices of sharing and reviewing to junior and senior RSEs.                                                                              |
```

2024-03-26 18:44 UTC, CaptainSifff commented
So, I think I have created in here a new state for discussion. On the ToDo List are:
- remove the duplication of SWLC. I'm not sure how it crept in.
- appease the spellchecker.
- And I've deferred the discussion of repos to #241 and #250.

After fixing these minor things(Or I do it in main) I could merge this MR and we can continue on the new issues.

What do you think @annalenalamprecht , @sdruskat , @jpthiele , @mhagdorn

2024-03-27 13:19 UTC, mhagdorn commented
this looks good to me. I do like the change to Software/Technical Skills

2024-03-27 16:08 UTC, mhagdorn commented
In the RSE tasks and responsibilities section we have under the "Proper development" bullet point SE skills. Do we want to change the abbreviation? We do have it in the glossary. I think it is fine since we are talking about actual software engineering tasks. But I did make we wonder given we went to great lengths to define technical skills.

2024-03-28 17:35 UTC, CaptainSifff approved these changes

2024-04-02 09:07 UTC, jpthiele approved these changes

2024-04-05 08:14 UTC, merged