Add ethics examination to research life cycle, fixes #261
CaptainSifff/paper_teaching-learning-RSE pull request #268
Opened 2024-04-23 05:21 UTC by jpthiele

2024-04-23 05:57 UTC, jpthiele commented
Related to #261

2024-04-23 10:10 UTC, MakisH approved these changes

2024-04-23 10:10 UTC, MakisH commented on competencies.md
> +can be an important step in the life-cycle of a specific project
```suggestion
can be an important step in the life-cycle of a specific project,
```

2024-04-26 11:26 UTC, CaptainSifff approved these changes

2024-04-26 11:26 UTC, CaptainSifff commented on competencies.md
> +can be an important step in the life-cycle of a specific project,
```suggestion
can be an important step in the life cycle of a specific project, 
```
since I just consistified that...

2024-04-26 14:52 UTC, mhagdorn requested changes
a long standing quibble (that should get changed) and a minor reformulation suggestion

2024-04-26 14:52 UTC, mhagdorn commented on competencies.md
> +Thereby they know that they are part of a bigger cycle
I think cycle isn't quite the right work here, what about 

they are part of a bigger group

2024-04-26 14:52 UTC, mhagdorn commented on competencies.md
> +They also know that the examination of ethical concerns
maybe

They may be asked to contribute to the ethical evaluation of a project to ensure integrity....

this makes it clear that they should be able to take an active role in the ethical evaluation of a research project

2024-04-29 04:49 UTC, jpthiele commented on competencies.md
> +Thereby they know that they are part of a bigger cycle
Group feels somehow too vague for me, 
how about one of the following 
- (human) endeavour
- undertaking

Or something along those lines to emphasize the collective effort of humanity that research ultimately is.

2024-04-29 07:16 UTC, mhagdorn commented on competencies.md
> +Thereby they know that they are part of a bigger cycle
Admittedly I was thinking strictly group of people. Your suggestion is much better. _Endeavour_ sounds a bit too grand to me, _undertaking_ is good.

2024-04-29 08:00 UTC, merged