Outreach and continuous learning
CaptainSifff/paper_teaching-learning-RSE pull request #33
Opened 2023-06-16 07:55 UTC by jngrad

Description of changes:
* explore efforts to incorporate RSE teaching in undergraduate statistics courses and high school biology courses
* discuss the effects of gamification on continuous learning and engagement in GitHub and Fedora
* expand bibliography on RSE teaching material and RSE good practices guides

2023-06-16 09:33 UTC, jngrad reviewed
Here is a summary of today's paper meeting lively discussion.

2023-06-16 09:33 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +- localizing RSE teaching material and RSE information in languages other than English, e.g. [Astigarraga2022], [ClementFontaine2019b], [Appel2021], [Haim2021] (FIXME: find more examples of teaching
* localized teaching material is certainly helpful to reach a wider audience
* look into ELIXIR for bioinformatics curricula (see #15)

2023-06-16 09:33 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +continuous integration status, or code quality indicators.
* personal badges could maybe help reduce skill gaps (fredo)
* look into [carpentry badges](https://software-carpentry.org/blog/2012/02/badges-finalized.html), which are not automated
* which institution would create RSE-badges?
   * badges could be based on certificates and get issued by certified institutions
* software badges serve entirely different purposes
   * code coverage badges and code maintainability/re-usability badges are actually useful for RSE grant proposals that require the software to be well tested and re-usable as a pre-requisite for funding
   * maybe move software badges to a self-contained paper about software policies and software quality assessment

2023-06-16 09:33 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +performance indicator debatable.
* automatically assigned badges are easy to game
* badges can fade after a few years (diminishing usefulness or relevance)
* badges should not be used as performance indicators (for hiring and/or career progress)
* an argument could be made for having *less* metrics (GitHub allows users to hide their badges)

2023-06-16 09:33 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +performance indicator debatable.
@jcohen02 said:
> Potential badge use cases:
> - Show knowledge or skills in a particular area or at a particular level
> - Show code meets one or more specific best practice requirements
> - Highlight a particular level or length of experience in a particular topic...

2023-06-19 19:27 UTC, jngrad reviewed
I've integrated all the feedback from last Friday's paper meeting. Some of the remarks are currently one-liners with a `FIXME:` tag, because they are big projects on their own and are getting a bit outside the original scope of identifying general tips and tricks for outreach. To make things more manageable, I would suggest merging this now and postpone further work to dedicated and self-contained PRs, namely:
* #15
* #35

2023-06-25 17:33 UTC, CaptainSifff reviewed
Thank You very much! See the inline mostly minor comments.

2023-06-25 17:33 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +core lessons are now officially part of the Software Carpentry [@CarpentriesSpanish].
```suggestion
core lessons are now officially part of the Software Carpentry material[@CarpentriesSpanish].
```

2023-06-25 17:33 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +covers topics such as pen-and-paper algorithm design, genomic database querying
```suggestion
cover topics such as pen-and-paper algorithm design, genomic database querying
```

2023-06-25 17:33 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +- adapting Carpentries and CodeRefinery material [@ENCCS2022] for RSEs from industry and HPC facilities
This sounds like something we should discuss in a next meeting. Maybe @samumantha has an idea for that.

2023-06-25 17:33 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +Some indicators could be used in GitHub/Lab to stimulate continuous learning or
```suggestion
Some indicators could be used used in collaborative Web platforms to stimulate continuous learning or
```

2023-06-25 17:33 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +
I feel your text is well-written and well-researched and addresses a lot of interesting questions.
Nevertheless I wonder whether this level of detail is required for this paper or whether it is suited better for the separate paper on badges in #35 ... Currently we don't utilize the notion of badges outside of this chapter. If we give such a big textual weight to badges we must almost utilize it outside of this chapter, like in defining which badges could be used in the progression competency tables, or which ones are required for being a teacher.
I would also like to hear the opinions of some others on this @jcohen02 ? @jpthiele?

2023-06-27 12:56 UTC, jngrad reviewed
At present the badge section is the main element blocking the merge. I agree this section isn't ready in its current state and needs more discussion, but at the same time, this PR grew a lot and now brings bibliographic records and various elements in the outreach discussion that I would like to build upon in upcoming PRs, and that would tie-in with other tickets on Elixir and Carpentries. While I could cherry-pick the needed parts, this approach would introduce unnecessary merge conflicts.

@CaptainSifff In the interest of resolving the situation, and avoiding extra work from resolving the growing merge conflicts, would it help if I reverted the changes to the badge section? We could always restore the content from the git history if we eventually decide that digital badges are relevant, and choose what to keep from it and how to best integrate it with the rest of the manuscript, in a dedicated PR.

2023-07-03 21:38 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +
Progress report:
- the off-topic paragraphs about commit charts and Fedora/GitHub badges have been removed
- the points discussed in https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/35#issuecomment-1607780631 have been added
- Ireland's PDF instructor badges and IBM badges have been added

2023-07-03 21:39 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +covers topics such as pen-and-paper algorithm design, genomic database querying
The typos you reported were addressed. Thanks!

2023-07-05 13:35 UTC, CaptainSifff commented
I will notify the others about your MR and I want to discuss it this friday. Thank You!

2023-07-07 12:32 UTC, jngrad reviewed
Summary from today's meeting:
- the digital badge section is still too long
- reframe as micro-accreditation / micro-credentials, since they do not need to be in the form of badges
- reframe as non-academic accreditation, since most of them are not awarded by academic institutions
- next steps:
   - have a subsection on digital certification as part of the RSE certification section, and better integrate it to the rest of the text (e.g. Carpentries to Carpentries badges)
   - further down in the paper, discuss the possibility of using the ontology of RSE competencies to craft digital certificates (similar to how HPC certification is currently being developed?)
- open questions: what infrastructure is needed to mint and verify these digital certificates? how to drive adoption of these certificates? data privacy concerns? how do you get accreditation as a RSE in industry, where contributions are usually not public? is the creation of additional metrics actually desirable? can these certificates have negative outcomes?
- links: [The Netherlands eScience Center Releases Job Profile and Role Description for Research Software Engineers](https://www.esciencecenter.nl/news/the-netherlands-escience-center-releases-job-profile-and-role-description-for-research-software-engineers/), [RSE Competencies Framework](https://github.com/RSEToolkit/rse-competencies-toolkit)

2023-07-17 09:49 UTC, mhagdorn requested changes
Thanks for the contribution and the very well researched additions. I have added some minor suggestions.

One thing I think isn't quite right yet is that the section "Identifying skills and pathways" is exclusively about HPC. I think some more generic introductory sentences would be great. You can then combine the info about HPC in the HPC section further down.

2023-07-17 13:08 UTC, mschwarzmeier commented on paper_teaching-learning-RSE.md
> +the first point of entry in the field. For example, statistics curricula can
This can only provide a very broad overview for the domain scientists studies. E.g. at the TU Darmstadt, there is a course `Fundamentals of Digitalisation` in the first semester, that with 4 CP covers a lot of topics related to RDM and RSE, with quite ambitious/demanding goals. In the 5th semester there is a `Hands on tutorial digitalization` with 2 CP which ("only") demands software versioning and archiving.

Link to the Modulbuch: https://www.maschinenbau.tu-darmstadt.de/studieren/downloads/index.de.jsp#einleitung_bachelor_maschinenbau


```suggestion
Teaching RSE in relevant undergraduate courses of domain scientists can be the first point of entry in the field.
However, considering many RSEs come from domain studies, only fundamental concepts (of RDM and RSE) can be explained to and experienced by all of them. Those interested in computer-related work or even programming will gain the special knowledge in classes and projects they choose.
For example, statistics curricula can
```

PS: `computer-related work` please rephrase

2023-07-17 13:13 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +the first point of entry in the field. For example, statistics curricula can
Hi all, just to notify you I've merged some MRs to the master, which might lead to conflicts...

2023-07-20 19:13 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +As an area that generally requires a range of advanced skills,
* this section should now look more balanced; extra paragraphs were added about:
   * competency frameworks developed in bioinformatics
   * an overview of domain-specific RSEs skill pathways (moved from the outlook)
* a new section on bioinformatics certification has been added after the HPC certification section
   * ideally, the certification chapter should grow independently of this one

2023-07-20 19:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +As an area that generally requires a range of advanced skills,
Great! we can sort this out with https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/15

2023-07-21 08:45 UTC, hvwaldow commented on paper_teaching-learning-RSE.md
> +or steer RSE behavior in a direction that would benefit all users of research software.
"Indicators" is not defined and also I think the word doesn#t apply to what is meant here ("competencies", badges). I don't think we should open the topic of experimental motivation enhancement for career development ("gamification"). I can't understand the last sentence about collaborative Web platforms and I also don't think there is consensus to establish instruments that "steer RSE behaviour".
I suggest to remove that paragraph.

2023-07-21 08:48 UTC, hvwaldow commented on paper_teaching-learning-RSE.md
> +As an area that generally requires a range of advanced skills,
:+1:

2023-07-21 08:53 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +or steer RSE behavior in a direction that would benefit all users of research software.
Agreed. Paragraph removed.

2023-07-21 09:06 UTC, hvwaldow commented on paper_teaching-learning-RSE.md
> +
There is some redundancy between 99-113 and the 3 following paragraphs. In particular the references are pretty much doubled in the same context, which seems weird. I suggest to Get rid of the "summary-listing" (104 - 109). And replace it with a somewhat extended version built from the following 3 paragraphs. The paragraph starting 120 belongs to the one above, it's both HPC. Can be shortened a bit.

Is it important to tell the history of the EMBL-EBI Competency Hub or would the info accessible from [@CompetencyHub; @Lloret-Llinares2022] also cover the info in Lines 128 - 133 sufficiently?

2023-07-21 09:13 UTC, hvwaldow commented on paper_teaching-learning-RSE.md
> +in the form of a digital badge [@Wilson2013a].
What is actually delivered is a certificate in the form of a PDF-page that looks like a certificate. I suggest to remove "digital badge" as it sounds a bit showy.

2023-07-21 10:34 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +
Main points from today's online meeting:
* move EMBL Competency Hub to the appendix, where we can explain its full history
* move HPC certification to the appendix

2023-07-21 10:35 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +in the form of a digital badge [@Wilson2013a].
Thanks! I could not find a picture of the instructor certificate, only that Carpentries refer to it as a "badge". I'll apply your suggestion.

2023-07-24 19:55 UTC, CaptainSifff commented
@jngrad I think I've synchronized all the open MRs into the main branch that we considered open last friday. You can now move forward, fix the conflicts, and merge your branch into main if you think it's  done.

2023-07-25 18:33 UTC, jngrad reviewed
The HPC certification, ELIXIR/BioExcel competencies, and digital certificates were moved to the appendix, with a link to them and a brief intro in the main body of the manuscript. Domain-specific Carpentry workshops are now mentioned in the outreach section, with [HPC Carpentry](https://www.hpc-carpentry.org/) and [Data Carpentry for Biologists](https://doi.org/10.21105/jose.00139) as examples. If I didn't miss anything, we should be good to go.

2023-07-26 14:08 UTC, merged