mention missing EOR metadata standard for RSE
CaptainSifff/paper_teaching-learning-RSE pull request #39
Opened 2023-06-23 10:56 UTC by knarrff

2023-06-23 11:36 UTC, jngrad approved these changes

2023-06-26 15:06 UTC, CaptainSifff requested changes

2023-06-26 15:06 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +- This needs another name: the resources above are also, at least mostly, open source.
What about "Further Open Educational resources"?
Then we should also have a categorization.
Ideally we have the big ones mentioned by name, and then a collection of the others. I still feel that Reprohack should go in there, I think it's not as big as e.g. Helmholtz.

2023-07-07 11:20 UTC, tobyhodges commented on paper_teaching-learning-RSE.md
> +This, in part, it due to a missing (metadata) standard to express these dependencies.
I would like to mention here [the `TrainingMaterial` specification](https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE) from Bioschemas, described in the recent paper in PLOS Computational Biology: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011120 

The Carpentries has a minimal implementation of this metadata specification in its lessons now, and is working towards implementing the full specification.

2023-07-14 14:18 UTC, CaptainSifff commented
@fiveop this is the MR about what we discussed today. Maybe you could bring it forward and up-to-date with master and the feedback?

2023-07-14 14:31 UTC, jngrad commented on paper_teaching-learning-RSE.md
> +This, in part, it due to a missing (metadata) standard to express these dependencies.
Maybe also relevant: a list of RSE training material databases like TesS and INTERSECT is developed in [`8ed2495c` (Open Source Resources)](https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/33/commits/e97d3a5c62c02f813f57c919a86e10fbf188571d#diff-8ed2495cf43a0bde383c279821d2482720d5a9b9c87db1f8ec3cff83552da037R177-R190)

2023-08-04 09:55 UTC, knarrff commented on paper_teaching-learning-RSE.md
> +- This needs another name: the resources above are also, at least mostly, open source.
This indeed should have another name. The suggested one is better, but am not convinced about that whole section. It mostly seems to talk about version control being used for most of the resources - above and otherwise.

2023-08-11 09:40 UTC, CaptainSifff approved these changes
I have to think about the new title of the section, but I think I get it....

2023-08-11 09:48 UTC, jngrad commented
Some aspects of FAIR have since been developed in the main document, e.g. training material databases in the second paragraph of [Open Source Resources](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/603e75f/paper_teaching-learning-RSE.md#open-source-resources), which is currently undergoing major changes in #86, in particular the FAIR discussion seems to have been removed (at the time I'm writing this comment).

2023-08-14 19:44 UTC, merged