Reword users
CaptainSifff/paper_teaching-learning-RSE pull request #51
Opened 2023-06-23 13:59 UTC by knarrff

2023-06-26 16:51 UTC, CaptainSifff requested changes

2023-06-26 16:51 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +Because of this, research software often has to be developed very closely to its users, the researchers.
In an attempt of shortening:
```suggestion
Research software is often developed as part of the research process itself, therefore it often has to be developed very closely to its users, the researchers.
```

2023-07-03 17:21 UTC, CaptainSifff requested changes

2023-07-03 17:21 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +Research software is often developed as part of the research process itself, therefore it often has to be developed very closely to its users, the researchers.
Sorry, to bother again, but we caught a duplication somehow here.

2023-07-07 11:08 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +This often means that it is hard to distinguish roles like developers and users because people often represent multiple roles.
There are too many 'often' in these two sentences, maybe we can invert the second one, e.g.
'Then, roles like developers and users can seldom be distinguished as most people represent multiple roles.'

2023-07-14 00:42 UTC, CaptainSifff commented
any updates, here?

2023-07-14 17:30 UTC, CaptainSifff commented
See #70

2023-07-17 13:08 UTC, merged