some light rewording
CaptainSifff/paper_teaching-learning-RSE pull request #54
Opened 2023-06-28 11:46 UTC by mhagdorn

2023-07-01 11:59 UTC, CaptainSifff requested changes

2023-07-01 11:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +We elaborate on some facets in tables. (FIXME: not sure about this sentence)
Yes, it's not good. the tables highlight various dimensions in which we can apply the competencies. Mind working that in?

2023-07-01 11:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +The RSE should be able to use public platforms to share the artefacts they have been created and invite the public to scrutinise them during public review.
Why the "been"....?

2023-07-01 11:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +An important part of reusability is that at least oneself, and ideally others, are able to understand what a piece of code aims to do and how to use the provided functionality. This is primarily achi
Thanks for breaking up my sentenes! :-)

2023-07-01 11:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +RSEs gain their reputation from their effectiveness to interact with their domain peers. Therefore, some curiosity together with a broad overview of the research field is required. Curiosity is also
1.) more linebreaks, while at it.
2.) I feel, that "Curiosity is also reflected when an RSE is actively trying out new tools." is closer to what I had in mind.

2023-07-01 11:59 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +Especially for data-driven research having software that is able to use existing data sets and repositories is a valuable part.
Now, that I'm looking at it....
What do you think of data sets, catalogues, and repositories ?

2023-07-01 13:57 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +We elaborate on some facets in tables. (FIXME: not sure about this sentence)
sure will have a go

2023-07-01 13:59 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +The RSE should be able to use public platforms to share the artefacts they have been created and invite the public to scrutinise them during public review.
ah, I probably tried to say "they have been creating" - although they "have created" might be better. I will think about that too

2023-07-03 09:05 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +RSEs gain their reputation from their effectiveness to interact with their domain peers. Therefore, some curiosity together with a broad overview of the research field is required. Curiosity is also
done

2023-07-03 09:15 UTC, mhagdorn commented
I think the structure of the Results section is difficult to see with the many subsections and without section numbers. Maybe we could turn the subsections with the individual skills into a description list

2023-07-03 11:31 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +Especially for data-driven research having software that is able to use existing data sets and repositories is a valuable part.
I have added a sentence specifically mentioning data sets and catalogues.  I think we could also mention that an RSE needs to be able to advise on data management. This could go into this section or, perhaps better, in the TEACH section.

2023-07-03 17:11 UTC, CaptainSifff commented on paper_teaching-learning-RSE.md
> +Especially for data-driven research having software that is able to use existing data sets and repositories is a valuable part.
I didn't make that a requirement on purpose. That leaves room for the specialization of an RDM-RSE, that's why the competencies have this generic domain repository thing that tries to encompass any digital infrastructure that is used in a domain.

2023-07-03 17:24 UTC, CaptainSifff commented
I should probably also notify you that #47 , #50, #51 deal with similar things.

2023-07-04 07:40 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +Especially for data-driven research having software that is able to use existing data sets and repositories is a valuable part.
a good point, makes sense

2023-07-04 08:30 UTC, mhagdorn commented
I very much like the wording of #51

2023-07-07 08:06 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +As it stands, the RSE role requires competencies in two fields: 1. the person
I find the numbering/ordering difficult. 
Because we also have people that 1. are software engineers ("SE") with 2. research skills ("R"). 
However, reading the initial sentence this was also not reflected, but I feel that the numbers highlight 
this even more.

2023-07-07 09:35 UTC, mhagdorn commented on paper_teaching-learning-RSE.md
> +As it stands, the RSE role requires competencies in two fields: 1. the person
Hmm, I didn't intend to order the categories but I do take your point. What about:

The role of an RSE lies somewhere on the spectrum between that of a researcher (the "R") and a software engineer (the "SE") and, therefore, requires competencies in both fields.

2023-07-07 09:38 UTC, jpthiele commented on paper_teaching-learning-RSE.md
> +As it stands, the RSE role requires competencies in two fields: 1. the person
I like it, it's brief but to the point!

2023-07-14 17:31 UTC, CaptainSifff commented
See #70

2023-07-17 13:08 UTC, closed without merging