added context (audience, purpose) to training material subsection
CaptainSifff/paper_teaching-learning-RSE pull request #64
Opened 2023-07-14 08:35 UTC by hvwaldow

I think a short remark to make the distinction between teaching material **used by RSEs to teach** and resources useful for RSEs to **learn** is in order, even though there is obviously a lot of overlap.

2023-07-14 09:04 UTC, jcohen02 requested changes
Great addition @hvwaldow - spotted a typo and added a couple of suggestions, hence requesting changes, but otherwise this looks good.

2023-07-14 09:04 UTC, jcohen02 commented on paper_teaching-learning-RSE.md
> +skills typically taught by RSEs.
I really like the addition of the link to this material. Maybe also add a note that these skills are important for anyone wanting to become an RSE? e.g.
```suggestion
skills typically taught by RSEs. The skills covered here also provide an important set of core capabilities for anyone looking to become an RSE.
```

2023-07-14 09:15 UTC, hvwaldow commented on paper_teaching-learning-RSE.md
> +skills typically taught by RSEs.
That this part ended here was some sort of runtime-condition and my bad branch management. It's a seperate PR: #65

2023-08-04 08:49 UTC, hvwaldow commented
@CaptainSifff I think this has been all merged now (contd. in #65) an therefore close this PR.

2023-08-04 08:49 UTC, closed without merging